### ISSUE TITLE
Platform error media_player.cambridge_cxn - Integration 'cambridge_cxn' not found.

### ISSUE THREAD

**Issue by jlukas99** [lievencoghe/cambridge_cxn#2]
I have error when check configuration so i cant restart machine

**Comment by Bvdmooren** [comment]
I had the same issue, adding a "version" to the Manifest JSON fixed it for me.

**Comment by Bvdmooren** [comment]
> I have error when check configuration so i cant restart machine

I had the same issue, adding a "version" to the Manifest JSON fixed it for me.

**Comment by ShallonTZ** [comment]
I am having this same issue but when I look inside the manifest. json there is already a 'version';

```
{
  "domain": "cambridge_cxn",
  "name": "Cambridge Audio CXN",
  "documentation": "https://github.com/lievencoghe/cambridge_cxn",
  "issue_tracker": "https://github.com/lievencoghe/cambridge_cxn/issues",
  "requirements": [],
  "dependencies": [],
  "codeowners": [
    "@lievencoghe"
  ],
  "version": "0.4",
  "iot_class": "local_push"
}
```

is this what you are talking about?

thanks for any help.

**Comment by antmarcha** [comment]
Same problem here, any solution?

**Comment by lievencoghe** [comment]
Hi, 
I have just committed version 0.5. I changed the manifest.json file to include some parameters that were missing before. Also use the new media_player.py file. 

Please try this version. Works fine on my end. Let me know how you get on!

Thanks,
Lieven
