### ISSUE TITLE
Bug report: Entity media_player.cambridge_cxn is using deprecated supported features values which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by JabeBRD** [lievencoghe/cambridge_cxn#5]
Got this error message in log.
`2024-06-06 13:10:46.868 WARNING (MainThread) [homeassistant.helpers.entity] Entity media_player.cambridge_cxn (<class 'custom_components.cambridge_cxn.media_player.CambridgeCXNDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE|STOP|PLAY|SHUFFLE_SET|REPEAT_SET: 318899>, please create a bug report at https://github.com/lievencoghe/cambridge_cxn/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`
Reference [https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation](url)

HA version:
```
Core               2024.6.0
Supervisor         2024.06.0
Operating System   12.3
Frontend           20240605.0
```

**Comment by lievencoghe** [comment]
Hi @JabeBRD 

Thanks for notifying me about this. I am now rewriting the component so this error will not appear anymore. Will let you know when the new version is available.

**Comment by lievencoghe** [comment]
Hi @JabeBRD 

I have committed a new version of the component that now uses the MediaPlayerEntityFeatures. Would you be so kind to test on your end and confirm you no longer get the error?

Thanks so much!

**Comment by JabeBRD** [comment]
Tried and got no error message.
Thank you.
