### ISSUE TITLE
Home Assistant HomeKit Bridge

### ISSUE THREAD

**Issue by dheckl** [lievencoghe/cambridge_cxn#6]
Is there any way to get the device exposed via HomeKit Bridge? Currently I am only able to control my Cambridge Audio Evo 150 via Home Assistant. I want to expose the device via HomeKit Bridge to HomeKit to be able to e.g. turn off the device. This is not possible with the native HomeKit integration via AirPlay 2.

**Comment by lievencoghe** [comment]
Hi @dheckl 

I just tested it by enablng the HomeKit Bridge on my Home Assistant. I can turn on/off my CXN just fine from the Apple Home app on my iPhone now.

**Comment by dheckl** [comment]
Just retested and now it works also on my side. We can close this issue. Thx!
